#ifndef DX_3D_BASE_OBJECTS_INIT_PARAM_INCLUDER_H_
#define DX_3D_BASE_OBJECTS_INIT_PARAM_INCLUDER_H_

#include "../Resource/DX3DResourceInitParamIncluder.h"

#endif // !DX_3D_BASE_OBJECTS_INIT_PARAM_INCLUDER_H_